/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205746;

public class Sanmoku {
    
    public static void main(String[] args) {
        var manager = new GameManager();
        manager.showBoard();

        /*
        while(true) {
            
        }
        */
    }


}
